export const RECEIVE_COMPETITIONS = 'RECEIVE_COMPETITIONS';
export const RECEIVE_COMPETITION_TEAMS = 'RECEIVE_COMPETITION_TEAMS';
export const RECEIVE_COMPETITION_LEAGUE_TABLE = 'RECEIVE_COMPETITION_LEAGUE_TABLE';
